spring:
  config:
    activate:
      on-profile: dev
  liquibase:
    enabled: true
    liquibase-schema: inv
    change-log: 'classpath:liquibase/changelog-master.xml'
    default-schema: inv
  jpa:
    show-sql: true
    properties:
      hibernate:
        cache:
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          use_second_level_cache: true
          use_query_cache: true
logging:
  config: classpath:logging/log4j2.dev.xml